apiVersion: v1
kind: ReplicationController
metadata:
  name: spring-boot-oauth-demo
  labels:
    name: spring-boot-oauth-demo
spec:
  replicas: 0
  selector:
    name: spring-boot-oauth-demo
  template:
    metadata:
      labels:
        name: spring-boot-oauth-demo
    spec:
      containers:
        - name: spring-boot-oauth-demo
          image: sphenrie/spring-boot-oauth2-demo:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
